//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.30 at 03:35:08 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://san.mibac.it/ead-san/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.mibac.san.ead_san;
